services:
  client:
    build: 
      context: .
      dockerfile: dev.Dockerfile
    command: dotnet run --project Client
    environment:
      - API_URL=http://nginx
      - IMAGE_API_PORT=5104
    ports:
      - 8080:8080
  api:
    build:
      context: .
      dockerfile: dev.Dockerfile
    command: dotnet run --project Api
    environment:
      - CONNECTION_STRING=Server=db;Database=postgres;User Id=postgres;Password=postgres;
      - IMAGE_API_URL=http://nginx
      - INTERVAL_DELAY=1000


  db:
    image: postgres:16
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  image-api1:
    build:
      context: .
      dockerfile: dev.Dockerfile
    command: dotnet run --project ImageAPI
    environment:
      - RUNNING_PORT=5105
      - INTERVAL_DELAY=1000
      - REDIRECT_ID=1
    ports:
      - 5105:5105
    volumes:
      - image_api_data1:/app/ImageAPI/wwwroot/images

  image-api2:
    build:
      context: .
      dockerfile: dev.Dockerfile
    command: dotnet run --project ImageAPI
    environment:
      - RUNNING_PORT=5106
      - INTERVAL_DELAY=1000
      - REDIRECT_ID=2
    ports:
      - 5106:5106
    volumes:
      - image_api_data2:/app/ImageAPI/wwwroot/images

  image-api3:
    build:
      context: .
      dockerfile: dev.Dockerfile
    command: dotnet run --project ImageAPI
    environment:
      - RUNNING_PORT=5107
      - INTERVAL_DELAY=1000
      - REDIRECT_ID=3
    ports:
      - 5107:5107
    volumes:
      - image_api_data3:/app/ImageAPI/wwwroot/images

  nginx:
    image: nginx
    ports:
      - 8555:80
    volumes:
      - ./chat-nginx-default.conf:/etc/nginx/conf.d/default.conf 

  redis-service:
    image: redis:latest
    container_name: redis_cache
    restart: always
    ports:
      - "7890:7890"
    command: redis-server --appendonly yes


volumes:
  postgres_data:
  image_api_data1:
  image_api_data2:
  image_api_data3: