apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: distributed-chat-bryce-carlos
  name: db-pvc
  labels:
    app: chat-db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
